// <auto-generated />
using System;
using Kroira.App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kroira.App.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260425024454_ConsolidateV2DataIntegrity")]
    partial class ConsolidateV2DataIntegrity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Kroira.App.Models.AppProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsKidsProfile")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("AppProfiles");
                });

            modelBuilder.Entity("Kroira.App.Models.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("Kroira.App.Models.CatchupPlaybackAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogicalContentKey")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProgramEndTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProgramStartTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProgramTitle")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderMode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderSource")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestKind")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedStreamUrl")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RoutingSummary")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WindowHours")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId", "RequestedAtUtc");

                    b.HasIndex("SourceProfileId", "RequestedAtUtc");

                    b.ToTable("CatchupPlaybackAttempts");
                });

            modelBuilder.Entity("Kroira.App.Models.Channel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AliasKeys")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("CatchupConfidence")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CatchupDetectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CatchupSource")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CatchupSummary")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("TEXT");

                    b.Property<int>("CatchupWindowHours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EnrichedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EpgChannelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EpgMatchConfidence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EpgMatchSource")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EpgMatchSummary")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("TEXT");

                    b.Property<int>("LogoConfidence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LogoSource")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogoSummary")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedIdentityKey")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderCatchupMode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderCatchupSource")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderEpgChannelId")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderLogoUrl")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.Property<string>("StreamUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SupportsCatchup")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EpgChannelId")
                        .HasDatabaseName("IX_Channels_EpgChannelId");

                    b.HasIndex("NormalizedIdentityKey")
                        .HasDatabaseName("IX_Channels_NormalizedIdentityKey");

                    b.HasIndex("NormalizedName")
                        .HasDatabaseName("IX_Channels_NormalizedName");

                    b.HasIndex("ProviderEpgChannelId")
                        .HasDatabaseName("IX_Channels_ProviderEpgChannelId");

                    b.HasIndex("ChannelCategoryId", "ProviderEpgChannelId")
                        .HasDatabaseName("IX_Channels_ChannelCategoryId_ProviderEpgChannelId");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("Kroira.App.Models.ChannelCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceProfileId")
                        .HasDatabaseName("IX_ChannelCategories_SourceProfileId");

                    b.ToTable("ChannelCategories");
                });

            modelBuilder.Entity("Kroira.App.Models.ContinueWatching", b =>
                {
                    b.Property<int>("ContentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContentType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastWatched")
                        .HasColumnType("TEXT");

                    b.Property<long>("PositionMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.ToTable("ContinueWatchings");
                });

            modelBuilder.Entity("Kroira.App.Models.DownloadJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ContentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContentType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxRetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("NextRetryAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputPath")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("StreamUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subtitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("TempOutputPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "Status", "RequestedAtUtc");

                    b.ToTable("DownloadJobs");
                });

            modelBuilder.Entity("Kroira.App.Models.EpgMappingDecision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("TEXT");

                    b.Property<int>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChannelIdentityKey")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Decision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProviderEpgChannelId")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasonSummary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StreamUrlHash")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.Property<int>("SuggestedConfidence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SuggestedMatchSource")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("XmltvChannelId")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("TEXT");

                    b.Property<string>("XmltvDisplayName")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceProfileId", "ChannelId");

                    b.HasIndex("SourceProfileId", "ChannelIdentityKey");

                    b.HasIndex("SourceProfileId", "ChannelId", "XmltvChannelId")
                        .IsUnique();

                    b.HasIndex("SourceProfileId", "StreamUrlHash", "XmltvChannelId");

                    b.ToTable("EpgMappingDecisions");
                });

            modelBuilder.Entity("Kroira.App.Models.EpgProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subtitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId", "StartTimeUtc")
                        .HasDatabaseName("IX_EpgPrograms_ChannelId_StartTimeUtc");

                    b.HasIndex("StartTimeUtc", "EndTimeUtc")
                        .HasDatabaseName("IX_EpgPrograms_StartTimeUtc_EndTimeUtc");

                    b.HasIndex("ChannelId", "StartTimeUtc", "EndTimeUtc")
                        .HasDatabaseName("IX_EpgPrograms_ChannelId_StartTimeUtc_EndTimeUtc");

                    b.ToTable("EpgPrograms");
                });

            modelBuilder.Entity("Kroira.App.Models.EpgSyncLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActiveMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActiveXmltvUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("ApprovedMatchCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentCoverageCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExactMatchCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailureStage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GuideSourceStatusJson")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("GuideWarningSummary")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSuccessAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchBreakdown")
                        .HasColumnType("TEXT");

                    b.Property<int>("MatchedChannelCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NextCoverageCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NormalizedMatchCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProgrammeCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResultCode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalLiveChannelCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnmatchedChannelCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeakMatchCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XmltvChannelCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceProfileId")
                        .IsUnique();

                    b.ToTable("EpgSyncLogs");
                });

            modelBuilder.Entity("Kroira.App.Models.Episode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StreamUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("Kroira.App.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContentType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogicalContentKey")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("TEXT");

                    b.Property<int>("PreferredSourceProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentType", "ContentId");

                    b.HasIndex("ProfileId", "ContentType", "ContentId");

                    b.HasIndex("ProfileId", "ContentType", "LogicalContentKey");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("Kroira.App.Models.FeatureEntitlement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OfflineSignature")
                        .HasColumnType("TEXT");

                    b.Property<string>("StoreSku")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FeatureEntitlements");
                });

            modelBuilder.Entity("Kroira.App.Models.LogicalOperationalCandidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContentId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLastKnownGood")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("LogicalOperationalStateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StreamUrl")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SupportsProxy")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceProfileId", "IsSelected");

                    b.HasIndex("LogicalOperationalStateId", "ContentId", "SourceProfileId")
                        .IsUnique();

                    b.ToTable("LogicalOperationalCandidates");
                });

            modelBuilder.Entity("Kroira.App.Models.LogicalOperationalState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CandidateCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsecutivePlaybackFailures")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContentType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastKnownGoodAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastKnownGoodContentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastKnownGoodScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastKnownGoodSourceProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastPlaybackFailureAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastPlaybackSuccessAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogicalContentKey")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<int>("PreferredContentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PreferredScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PreferredSourceProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PreferredUpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecoveryAction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecoverySummary")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectionSummary")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SnapshotEvaluatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentType", "LogicalContentKey")
                        .IsUnique();

                    b.ToTable("LogicalOperationalStates");
                });

            modelBuilder.Entity("Kroira.App.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackdropUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalTitleKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentKind")
                        .HasColumnType("TEXT");

                    b.Property<string>("DedupFingerprint")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genres")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImdbId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("MetadataUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalLanguage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Overview")
                        .HasColumnType("TEXT");

                    b.Property<double>("Popularity")
                        .HasColumnType("REAL");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawSourceCategoryName")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawSourceTitle")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StreamUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("TmdbBackdropPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("TmdbId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TmdbPosterPath")
                        .HasColumnType("TEXT");

                    b.Property<double>("VoteAverage")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalTitleKey");

                    b.HasIndex("DedupFingerprint");

                    b.HasIndex("MetadataUpdatedAt");

                    b.HasIndex("SourceProfileId");

                    b.HasIndex("TmdbId");

                    b.HasIndex("SourceProfileId", "CanonicalTitleKey");

                    b.HasIndex("SourceProfileId", "ContentKind");

                    b.HasIndex("SourceProfileId", "ExternalId");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("Kroira.App.Models.ParentalControlSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HideLockedContent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsKidsSafeMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LockedCategoryIdsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("LockedSourceIdsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("PinHash")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("ParentalControlSettings");
                });

            modelBuilder.Entity("Kroira.App.Models.PlaybackProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ContentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContentType")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastWatched")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogicalContentKey")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<long>("PositionMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PreferredSourceProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("WatchStateOverride")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContentType", "ContentId");

                    b.HasIndex("ProfileId", "ContentType", "ContentId");

                    b.HasIndex("ProfileId", "ContentType", "LogicalContentKey");

                    b.ToTable("PlaybackProgresses");
                });

            modelBuilder.Entity("Kroira.App.Models.RecordingJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChannelName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxRetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("NextRetryAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputPath")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("StreamUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("TempOutputPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "Status", "StartTimeUtc");

                    b.ToTable("RecordingJobs");
                });

            modelBuilder.Entity("Kroira.App.Models.SchemaVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsValidated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SchemaVersions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppliedAt = new DateTime(2026, 4, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsValidated = true,
                            VersionNumber = 1
                        });
                });

            modelBuilder.Entity("Kroira.App.Models.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("Kroira.App.Models.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackdropUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalTitleKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DedupFingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FirstAirDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImdbId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("MetadataUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Overview")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Popularity")
                        .HasColumnType("REAL");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RawSourceCategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RawSourceTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TmdbBackdropPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TmdbId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TmdbPosterPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("VoteAverage")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalTitleKey");

                    b.HasIndex("DedupFingerprint");

                    b.HasIndex("MetadataUpdatedAt");

                    b.HasIndex("SourceProfileId");

                    b.HasIndex("TmdbId");

                    b.HasIndex("SourceProfileId", "CanonicalTitleKey");

                    b.HasIndex("SourceProfileId", "ContentKind");

                    b.HasIndex("SourceProfileId", "ExternalId");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("Kroira.App.Models.SourceAcquisitionEvidence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AliasKeys")
                        .IsRequired()
                        .HasMaxLength(1600)
                        .HasColumnType("TEXT");

                    b.Property<int>("Confidence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdentityKey")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatchedTarget")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchedValue")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedCategory")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("TEXT");

                    b.Property<int>("Outcome")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawCategory")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawName")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("RuleCode")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceAcquisitionRunId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stage")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceAcquisitionRunId", "SortOrder");

                    b.ToTable("SourceAcquisitionEvidence");
                });

            modelBuilder.Entity("Kroira.App.Models.SourceAcquisitionProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatchingSummary")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizationSummary")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PreferLastKnownGoodRollback")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PreferProxyDuringValidation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProfileKey")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileLabel")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsRegexMatching")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SuppressionSummary")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidationSummary")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceProfileId")
                        .IsUnique();

                    b.ToTable("SourceAcquisitionProfiles");
                });

            modelBuilder.Entity("Kroira.App.Models.SourceAcquisitionRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AcceptedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AliasMatchCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CatalogSummary")
                        .IsRequired()
                        .HasMaxLength(280)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DemotedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EpisodeCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FuzzyMatchCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GuideSummary")
                        .IsRequired()
                        .HasMaxLength(280)
                        .HasColumnType("TEXT");

                    b.Property<int>("LiveCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(420)
                        .HasColumnType("TEXT");

                    b.Property<int>("MovieCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProbeFailureCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProbeSuccessCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProfileKey")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileLabel")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<int>("RawItemCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RegexMatchCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoutingSummary")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<int>("Scope")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeriesCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SuppressedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Trigger")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnmatchedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ValidationRoutingSummary")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidationSummary")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<int>("WarningCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceProfileId", "StartedAtUtc");

                    b.ToTable("SourceAcquisitionRuns");
                });

            modelBuilder.Entity("Kroira.App.Models.SourceChannelEnrichmentRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AliasKeys")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("EpgMatchConfidence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EpgMatchSource")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EpgMatchSummary")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentityKey")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastAppliedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("LogoConfidence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LogoSource")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogoSummary")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchedXmltvChannelId")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchedXmltvDisplayName")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchedXmltvIconUrl")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderEpgChannelId")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderLogoUrl")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedLogoUrl")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceProfileId", "IdentityKey")
                        .IsUnique();

                    b.ToTable("SourceChannelEnrichmentRecords");
                });

            modelBuilder.Entity("Kroira.App.Models.SourceCredential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanionMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanionScope")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanionUrl")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectedEpgUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("EpgMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EpgUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("FallbackEpgUrls")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("M3uImportMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProxyScope")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProxyUrl")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StalkerApiUrl")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.Property<string>("StalkerDeviceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("StalkerLocale")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("StalkerMacAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("StalkerSerialNumber")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("StalkerTimezone")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceProfileId")
                        .IsUnique();

                    b.ToTable("SourceCredentials");
                });

            modelBuilder.Entity("Kroira.App.Models.SourceHealthComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponentType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HealthyCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IssueCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RelevantCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceHealthReportId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceHealthReportId", "ComponentType")
                        .IsUnique();

                    b.ToTable("SourceHealthComponents");
                });

            modelBuilder.Entity("Kroira.App.Models.SourceHealthIssue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AffectedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(280)
                        .HasColumnType("TEXT");

                    b.Property<string>("SampleItems")
                        .IsRequired()
                        .HasMaxLength(280)
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceHealthReportId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceHealthReportId");

                    b.ToTable("SourceHealthIssues");
                });

            modelBuilder.Entity("Kroira.App.Models.SourceHealthProbe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CandidateCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FailureCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HttpErrorCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProbeType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ProbedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("SampleSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceHealthReportId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SuccessCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeoutCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TransportErrorCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceHealthReportId", "ProbeType")
                        .IsUnique();

                    b.ToTable("SourceHealthProbes");
                });

            modelBuilder.Entity("Kroira.App.Models.SourceHealthReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelsWithCurrentProgramCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelsWithEpgMatchCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelsWithLogoCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelsWithNextProgramCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DuplicateCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EvaluatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("HealthScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HealthState")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImportResultSummary")
                        .IsRequired()
                        .HasMaxLength(280)
                        .HasColumnType("TEXT");

                    b.Property<int>("InvalidStreamCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSuccessfulSyncAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncAttemptAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatusSummary")
                        .IsRequired()
                        .HasMaxLength(280)
                        .HasColumnType("TEXT");

                    b.Property<int>("SuspiciousEntryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TopIssueSummary")
                        .IsRequired()
                        .HasMaxLength(360)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalChannelCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalMovieCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalSeriesCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ValidationSummary")
                        .IsRequired()
                        .HasMaxLength(280)
                        .HasColumnType("TEXT");

                    b.Property<int>("WarningCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceProfileId")
                        .IsUnique();

                    b.ToTable("SourceHealthReports");
                });

            modelBuilder.Entity("Kroira.App.Models.SourceProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSync")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SourceProfiles");
                });

            modelBuilder.Entity("Kroira.App.Models.SourceProtectedCredentialSecret", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtectedValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtectionScheme")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceProfileId", "Name")
                        .IsUnique();

                    b.ToTable("SourceProtectedCredentialSecrets");
                });

            modelBuilder.Entity("Kroira.App.Models.SourceSyncState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutoRefreshFailureCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutoRefreshState")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AutoRefreshSummary")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorLog")
                        .HasColumnType("TEXT");

                    b.Property<int>("HttpStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastAttempt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastAutoRefreshAttemptAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastAutoRefreshSuccessAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextAutoRefreshDueAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceProfileId")
                        .IsUnique();

                    b.ToTable("SourceSyncStates");
                });

            modelBuilder.Entity("Kroira.App.Models.StalkerPortalSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscoveredApiUrl")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastHandshakeAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastProfileSyncAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSummary")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<int>("LiveCategoryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("MovieCategoryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PortalName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<string>("PortalVersion")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("SeriesCategoryCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsLive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsMovies")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsSeries")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceProfileId")
                        .IsUnique();

                    b.ToTable("StalkerPortalSnapshots");
                });

            modelBuilder.Entity("Kroira.App.Models.CatchupPlaybackAttempt", b =>
                {
                    b.HasOne("Kroira.App.Models.SourceProfile", null)
                        .WithMany()
                        .HasForeignKey("SourceProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kroira.App.Models.Channel", b =>
                {
                    b.HasOne("Kroira.App.Models.ChannelCategory", null)
                        .WithMany("Channels")
                        .HasForeignKey("ChannelCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kroira.App.Models.EpgMappingDecision", b =>
                {
                    b.HasOne("Kroira.App.Models.SourceProfile", null)
                        .WithMany()
                        .HasForeignKey("SourceProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kroira.App.Models.EpgProgram", b =>
                {
                    b.HasOne("Kroira.App.Models.Channel", null)
                        .WithMany("EpgPrograms")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kroira.App.Models.EpgSyncLog", b =>
                {
                    b.HasOne("Kroira.App.Models.SourceProfile", null)
                        .WithOne()
                        .HasForeignKey("Kroira.App.Models.EpgSyncLog", "SourceProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kroira.App.Models.Episode", b =>
                {
                    b.HasOne("Kroira.App.Models.Season", null)
                        .WithMany("Episodes")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kroira.App.Models.LogicalOperationalCandidate", b =>
                {
                    b.HasOne("Kroira.App.Models.LogicalOperationalState", "State")
                        .WithMany("Candidates")
                        .HasForeignKey("LogicalOperationalStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("Kroira.App.Models.Season", b =>
                {
                    b.HasOne("Kroira.App.Models.Series", null)
                        .WithMany("Seasons")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kroira.App.Models.SourceAcquisitionEvidence", b =>
                {
                    b.HasOne("Kroira.App.Models.SourceAcquisitionRun", "Run")
                        .WithMany("Evidence")
                        .HasForeignKey("SourceAcquisitionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Kroira.App.Models.SourceAcquisitionProfile", b =>
                {
                    b.HasOne("Kroira.App.Models.SourceProfile", null)
                        .WithOne()
                        .HasForeignKey("Kroira.App.Models.SourceAcquisitionProfile", "SourceProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kroira.App.Models.SourceAcquisitionRun", b =>
                {
                    b.HasOne("Kroira.App.Models.SourceProfile", null)
                        .WithMany()
                        .HasForeignKey("SourceProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kroira.App.Models.SourceChannelEnrichmentRecord", b =>
                {
                    b.HasOne("Kroira.App.Models.SourceProfile", null)
                        .WithMany()
                        .HasForeignKey("SourceProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kroira.App.Models.SourceCredential", b =>
                {
                    b.HasOne("Kroira.App.Models.SourceProfile", null)
                        .WithOne()
                        .HasForeignKey("Kroira.App.Models.SourceCredential", "SourceProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kroira.App.Models.SourceHealthComponent", b =>
                {
                    b.HasOne("Kroira.App.Models.SourceHealthReport", "Report")
                        .WithMany("Components")
                        .HasForeignKey("SourceHealthReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("Kroira.App.Models.SourceHealthIssue", b =>
                {
                    b.HasOne("Kroira.App.Models.SourceHealthReport", "Report")
                        .WithMany("Issues")
                        .HasForeignKey("SourceHealthReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("Kroira.App.Models.SourceHealthProbe", b =>
                {
                    b.HasOne("Kroira.App.Models.SourceHealthReport", "Report")
                        .WithMany("Probes")
                        .HasForeignKey("SourceHealthReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("Kroira.App.Models.SourceHealthReport", b =>
                {
                    b.HasOne("Kroira.App.Models.SourceProfile", null)
                        .WithOne()
                        .HasForeignKey("Kroira.App.Models.SourceHealthReport", "SourceProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kroira.App.Models.SourceProtectedCredentialSecret", b =>
                {
                    b.HasOne("Kroira.App.Models.SourceProfile", null)
                        .WithMany()
                        .HasForeignKey("SourceProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kroira.App.Models.SourceSyncState", b =>
                {
                    b.HasOne("Kroira.App.Models.SourceProfile", null)
                        .WithOne()
                        .HasForeignKey("Kroira.App.Models.SourceSyncState", "SourceProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kroira.App.Models.StalkerPortalSnapshot", b =>
                {
                    b.HasOne("Kroira.App.Models.SourceProfile", null)
                        .WithOne()
                        .HasForeignKey("Kroira.App.Models.StalkerPortalSnapshot", "SourceProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kroira.App.Models.Channel", b =>
                {
                    b.Navigation("EpgPrograms");
                });

            modelBuilder.Entity("Kroira.App.Models.ChannelCategory", b =>
                {
                    b.Navigation("Channels");
                });

            modelBuilder.Entity("Kroira.App.Models.LogicalOperationalState", b =>
                {
                    b.Navigation("Candidates");
                });

            modelBuilder.Entity("Kroira.App.Models.Season", b =>
                {
                    b.Navigation("Episodes");
                });

            modelBuilder.Entity("Kroira.App.Models.Series", b =>
                {
                    b.Navigation("Seasons");
                });

            modelBuilder.Entity("Kroira.App.Models.SourceAcquisitionRun", b =>
                {
                    b.Navigation("Evidence");
                });

            modelBuilder.Entity("Kroira.App.Models.SourceHealthReport", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("Issues");

                    b.Navigation("Probes");
                });
#pragma warning restore 612, 618
        }
    }
}
