// <auto-generated />
using Kroira.App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Kroira.App.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AddSourceCompanionRelay
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            MigrationDesignerBackfillSupport.BuildCurrent(modelBuilder);
#pragma warning restore 612, 618
        }
    }
}
